// <auto-generated />
using System;
using AccesoDeDatos.Repositorios.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccesoDeDatos.Migrations
{
    [DbContext(typeof(GestorContext))]
    [Migration("20251219022521_ProbandoRestrinccionesEF3")]
    partial class ProbandoRestrinccionesEF3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LogicaDeNegocios.Configuracion", b =>
                {
                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Nombre");

                    b.ToTable("Configuracions");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.Apiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Latitud")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitud")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UbicacionDeReferencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Apiarios");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.Colmena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApiarioId")
                        .HasColumnType("int");

                    b.Property<int?>("ApiarioId1")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaInstalacionSensores")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApiarioId");

                    b.HasIndex("ApiarioId1");

                    b.ToTable("Colmenas");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.Cuadro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ColmenaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ColmenaId");

                    b.ToTable("Cuadros");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.MedicionColmena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColmenaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaMedicion")
                        .HasColumnType("datetime2");

                    b.Property<float>("Peso")
                        .HasColumnType("real");

                    b.Property<float>("TempExterna")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ColmenaId");

                    b.ToTable("MedicionColmenas");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaNotificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistroAsociadoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegistroAsociadoId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.Registro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Registros");

                    b.HasDiscriminator().HasValue("Registro");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.Sensor", b =>
                {
                    b.Property<int>("SensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SensorId"));

                    b.Property<string>("TipoSensor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SensorId");

                    b.ToTable("Sensores");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.SensorPorCuadro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaMedicion")
                        .HasColumnType("datetime2");

                    b.Property<float>("TempInterna1")
                        .HasColumnType("real");

                    b.Property<float>("TempInterna2")
                        .HasColumnType("real");

                    b.Property<float>("TempInterna3")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("SensorPorCuadros");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.RegistroSensor", b =>
                {
                    b.HasBaseType("LogicaDeNegocios.Entidades.Registro");

                    b.HasDiscriminator().HasValue("RegistroSensor");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.Apiario", b =>
                {
                    b.HasOne("LogicaDeNegocios.Entidades.Usuario", null)
                        .WithMany("Apiarios")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.Colmena", b =>
                {
                    b.HasOne("LogicaDeNegocios.Entidades.Apiario", "Apiario")
                        .WithMany()
                        .HasForeignKey("ApiarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogicaDeNegocios.Entidades.Apiario", null)
                        .WithMany("Colmenas")
                        .HasForeignKey("ApiarioId1");

                    b.Navigation("Apiario");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.Cuadro", b =>
                {
                    b.HasOne("LogicaDeNegocios.Entidades.Colmena", null)
                        .WithMany("Cuadros")
                        .HasForeignKey("ColmenaId");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.MedicionColmena", b =>
                {
                    b.HasOne("LogicaDeNegocios.Entidades.Colmena", null)
                        .WithMany("Mediciones")
                        .HasForeignKey("ColmenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.Notificacion", b =>
                {
                    b.HasOne("LogicaDeNegocios.Entidades.Registro", "RegistroAsociado")
                        .WithMany()
                        .HasForeignKey("RegistroAsociadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistroAsociado");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.Apiario", b =>
                {
                    b.Navigation("Colmenas");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.Colmena", b =>
                {
                    b.Navigation("Cuadros");

                    b.Navigation("Mediciones");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.Usuario", b =>
                {
                    b.Navigation("Apiarios");
                });
#pragma warning restore 612, 618
        }
    }
}
