// <auto-generated />
using System;
using AccesoDeDatos.Repositorios.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccesoDeDatos.Migrations
{
    [DbContext(typeof(GestorContext))]
    [Migration("20260119000115_se_cambio_agregar")]
    partial class se_cambio_agregar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LogicaDeNegocios.Configuracion", b =>
                {
                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Nombre");

                    b.ToTable("Configuracions");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.Apiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Latitud")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitud")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UbicacionDeReferencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Apiarios");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.Colmena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApiarioId")
                        .HasColumnType("int");

                    b.Property<int>("Condicion")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaInstalacionSensores")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApiarioId");

                    b.ToTable("Colmenas");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.Cuadro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColmenaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ColmenaId");

                    b.ToTable("Cuadros");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.MedicionColmena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColmenaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaMedicion")
                        .HasColumnType("datetime2");

                    b.Property<float>("Peso")
                        .HasColumnType("real");

                    b.Property<float>("TempExterna")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ColmenaId");

                    b.ToTable("MedicionColmenas");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaNotificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistroAsociadoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioReceptorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegistroAsociadoId");

                    b.HasIndex("UsuarioReceptorId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.Registro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<bool>("EstaPendiente")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Registros");

                    b.HasDiscriminator().HasValue("Registro");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.Sensor", b =>
                {
                    b.Property<int>("SensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SensorId"));

                    b.Property<int>("ColmenaId")
                        .HasColumnType("int");

                    b.Property<int>("CuadroId")
                        .HasColumnType("int");

                    b.Property<string>("TipoSensor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SensorId");

                    b.HasIndex("ColmenaId");

                    b.HasIndex("CuadroId");

                    b.ToTable("Sensores");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.SensorPorCuadro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CuadroId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaMedicion")
                        .HasColumnType("datetime2");

                    b.Property<int>("SensorId")
                        .HasColumnType("int");

                    b.Property<float>("TempInterna1")
                        .HasColumnType("real");

                    b.Property<float>("TempInterna2")
                        .HasColumnType("real");

                    b.Property<float>("TempInterna3")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CuadroId");

                    b.HasIndex("SensorId");

                    b.ToTable("SensorPorCuadros");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MedioDeComunicacionDePreferencia")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroApicultor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.RegistroMedicionColmena", b =>
                {
                    b.HasBaseType("LogicaDeNegocios.Entidades.Registro");

                    b.Property<int>("MedicionColmenaId")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("MensajesAlerta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ValorEstaEnRangoBorde")
                        .HasColumnType("bit");

                    b.HasIndex("MedicionColmenaId");

                    b.HasDiscriminator().HasValue("RegistroMedicionColmena");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.RegistroSensor", b =>
                {
                    b.HasBaseType("LogicaDeNegocios.Entidades.Registro");

                    b.PrimitiveCollection<string>("MensajesAlerta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ValorEstaEnRangoBorde")
                        .HasColumnType("bit");

                    b.Property<int?>("sensorPorCuadroId")
                        .HasColumnType("int");

                    b.HasIndex("sensorPorCuadroId");

                    b.ToTable("Registros", t =>
                        {
                            t.Property("MensajesAlerta")
                                .HasColumnName("RegistroSensor_MensajesAlerta");

                            t.Property("ValorEstaEnRangoBorde")
                                .HasColumnName("RegistroSensor_ValorEstaEnRangoBorde");
                        });

                    b.HasDiscriminator().HasValue("RegistroSensor");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.Apiario", b =>
                {
                    b.HasOne("LogicaDeNegocios.Entidades.Usuario", "Usuario")
                        .WithMany("Apiarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.Colmena", b =>
                {
                    b.HasOne("LogicaDeNegocios.Entidades.Apiario", "Apiario")
                        .WithMany("Colmenas")
                        .HasForeignKey("ApiarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Apiario");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.Cuadro", b =>
                {
                    b.HasOne("LogicaDeNegocios.Entidades.Colmena", "Colmena")
                        .WithMany("Cuadros")
                        .HasForeignKey("ColmenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colmena");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.MedicionColmena", b =>
                {
                    b.HasOne("LogicaDeNegocios.Entidades.Colmena", "Colmena")
                        .WithMany("Mediciones")
                        .HasForeignKey("ColmenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colmena");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.Notificacion", b =>
                {
                    b.HasOne("LogicaDeNegocios.Entidades.Registro", "RegistroAsociado")
                        .WithMany()
                        .HasForeignKey("RegistroAsociadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogicaDeNegocios.Entidades.Usuario", "UsuarioReceptor")
                        .WithMany()
                        .HasForeignKey("UsuarioReceptorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistroAsociado");

                    b.Navigation("UsuarioReceptor");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.Sensor", b =>
                {
                    b.HasOne("LogicaDeNegocios.Entidades.Colmena", "Colmena")
                        .WithMany()
                        .HasForeignKey("ColmenaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LogicaDeNegocios.Entidades.Cuadro", "Cuadro")
                        .WithMany()
                        .HasForeignKey("CuadroId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Colmena");

                    b.Navigation("Cuadro");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.SensorPorCuadro", b =>
                {
                    b.HasOne("LogicaDeNegocios.Entidades.Cuadro", "Cuadro")
                        .WithMany("Mediciones")
                        .HasForeignKey("CuadroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogicaDeNegocios.Entidades.Sensor", "Sensor")
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuadro");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.RegistroMedicionColmena", b =>
                {
                    b.HasOne("LogicaDeNegocios.Entidades.MedicionColmena", "MedicionColmena")
                        .WithMany()
                        .HasForeignKey("MedicionColmenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicionColmena");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.RegistroSensor", b =>
                {
                    b.HasOne("LogicaDeNegocios.Entidades.SensorPorCuadro", "sensorPorCuadro")
                        .WithMany()
                        .HasForeignKey("sensorPorCuadroId");

                    b.Navigation("sensorPorCuadro");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.Apiario", b =>
                {
                    b.Navigation("Colmenas");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.Colmena", b =>
                {
                    b.Navigation("Cuadros");

                    b.Navigation("Mediciones");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.Cuadro", b =>
                {
                    b.Navigation("Mediciones");
                });

            modelBuilder.Entity("LogicaDeNegocios.Entidades.Usuario", b =>
                {
                    b.Navigation("Apiarios");
                });
#pragma warning restore 612, 618
        }
    }
}
